 let resumeMoudleMock = [
    {
    title:'教育经历',
    expand:true,
    inputList:[{
        school:'',
        major:'',
        degree:'',
        academy:'',
        city:'',
        Time:{
            startTime:'',
            endTime:''
        },
        richText:''
    },
    {
        school:'',
        major:'',
        degree:'',
        academy:'',
        Time:{
            startTime:'',
            endTime:''
        },
        richText:''
    }]
},
{
    title:'工作经历',
    expand:true,
    inputList:[{
        school:'',
        major:'',
        degree:'',
        academy:'',
        Time:{
            startTime:'',
            endTime:''
        },
        richText:''
    }]
}]

export default resumeMoudleMock