 let resumeMoudleMock = [
    {
    isShow:true,
    title:'教育经历',
    expand:true,
    inputList:[{
        school:'',
        major:'',
        degree:'',
        academy:'',
        city:'',
            startTime:'',
            endTime:'',
        richText:''
    },
    {
        school:'',
        major:'',
        degree:'',
        academy:'',
        startTime:'',
        endTime:'',
        richText:''
    }]
},
{
    isShow:true,
    title:'工作经历',
    expand:true,
    inputList:[{
        school:'',
        major:'',
        degree:'',
        academy:'',
            startTime:'',
            endTime:'',
        richText:''
    }]
}
,
{
    isShow:true,
    title:'项目经历',
    expand:true,
    inputList:[{
        school:'',
        major:'',
        degree:'',
        academy:'',
            startTime:'',
            endTime:'',
        richText:''
    }]
},
{
    isShow:true,
    title:'个人总结',
    expand:true,
    inputList:[{
        school:'',
        major:'',
        degree:'',
        academy:'',
            startTime:'',
            endTime:'',
        richText:''
    }]
}
]

export default resumeMoudleMock